# Generated by Django 5.2.14 on 2026-05-31 23:50

import sissub.models.currency
import sissub.models.service
import sissub.models.subscription
import sissub.models.subscription_user
import sissub.models.user_profile
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[sissub.models.currency.validar_codigo_moneda])),
                ('symbol', models.CharField(max_length=5)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[sissub.models.service.validar_nombre])),
                ('is_custom', models.BooleanField(db_column='iscustom', default=False)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[sissub.models.subscription.validar_monto_positivo])),
                ('billing_cycle', models.CharField(db_column='billingcycle', max_length=50)),
                ('next_billing_date', models.DateField(db_column='nextbillingdate', validators=[sissub.models.subscription.validar_fecha_futura])),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[sissub.models.subscription_user.validar_porcentaje])),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[sissub.models.user_profile.validar_correo])),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
